version: '3.8'

name: cici-workbench

volumes:
  cici-workbench-data:
    name: cici-workbench-data
  cici-workbench-secrets:
    name: cici-workbench-secrets
  cici-workbench-backups:
    name: cici-workbench-backups

services:
  cici-workbench:
    image: cici/cici-workbench:latest
    init: true
    container_name: cici-workbench
    restart: always
    ports:
      - "127.0.0.1:8088:8088"
    # environment:
    #   - QWENPAW_AUTH_ENABLED=true
    #   - QWENPAW_AUTH_USERNAME=admin
    #   - QWENPAW_AUTH_PASSWORD=yourpassword
    volumes:
      - cici-workbench-data:/app/working
      - cici-workbench-secrets:/app/working.secret
      - cici-workbench-backups:/app/working.backups
